/**
 *
 * @format
 * @description :  Account Account Trigger Helper
 * NOTE FOR TEST COVERAGE
 * @author : david@experancepartners.com
 * @group :
 * @last modified on  : 08-05-2022
 * @last modified by  : david@experancepartners.com
 *  * 1.0   08-05-2022   david@experancepartners.com   Initial Version
 *
 */
public without sharing class Account_Account extends TriggerHelperBase {
    // just exists so the TriggerHelperBase is used.  Sad really.  But it is ok.
    // a real account trigger will come some day and replace this.
    public override void bulkAfter() {
    }
}
