/**
 *
 * @format
 * @description :  Trigger State Interface
 * Interface used in the virualization of Trigger State.
 * @author : david@experancepartners.com
 * @group :
 * @last modified on  : 08-15-2022
 * @last modified by  : david@experancepartners.com
 *  * 1.0   08-15-2022   david@experancepartners.com   Initial Version
 *
 **/
public interface iTriggerState {
    Integer countAt(String tState);
}
